### PR TITLE
fix: the unstable issue due to only the first registered destroy method would take affect

### PR DESCRIPTION
**Pull request by saury**
Would it be nice to keep the pre IVY version?

### CODE REVIEW

**Comment by NetanelBasal** [comment]
Please explain what is the issue that this PR fixes. Show a code example. Thanks.

**Comment by saury** [comment]
Here's a quick and simple example. In any angular component use with View Engine:

```typescript
// In xx.component.ts file
// ...
test1() {
    interval(1000)
      .pipe(untilDestroyed(this))
      .subscribe(console.log);
  }

test2() {
  setTimeout(() => {
    this.reset();
  }, 4000);

  interval(1000)
    .pipe(untilDestroyed(this, 'reset'))
    .subscribe(console.log);
}

reset() {}

ngOnInit() {
  this.test1();
  this.test2();
}

ngOnDestroy() {}
// ...
```

My expecting behavior is that the subscription in test1 last until this component destroyed and the one in test2 last 4 seconds right after this component been initialized.

With the latest version of pre IVY version, the subscription in test2 will never be unsubscribed.

What's more, if I shift the sequence like this:

```typescript
ngOnInit() {
  this.test2();
  this.test1();
}
```

Both of them would be unsubscribed after 4 sec.

**Comment by NetanelBasal** [comment]
You are using the wrong package. This package is for Ivy.

**Comment by saury** [comment]
@NetanelBasal 
I visited https://github.com/NetanelBasal/ngx-take-until-destroy and it leads me to this repo. 
So do you have any idea where I can find this repo.

**Comment by NetanelBasal** [comment]
It's deprecated.

**Comment by saury** [comment]
So back to my proposal, as this was not mentioned deprecated in readme file. 
Would it be nice to keep the pre IVY version live by creating another branch or whatever.

**Comment by arturovt** [comment]
Can it be closed?

**Comment by NetanelBasal** [comment]
Yes

**Pull request closed without merging**
