### PR TITLE
docs: remove Angular 10 compatibility section

### PR DESCRIPTION
**Pull request by arturovt**

### CODE REVIEW

**Review by NetanelBasal — APPROVED** [review]

**Comment by arturovt** [comment]
@NetanelBasal yo is there anything wrong with actions CI?

**Comment by NetanelBasal** [comment]
It seems like a GitHub bug.

**Comment by arturovt** [comment]
I'll try to update the OS in another PR

**Comment by NetanelBasal** [comment]
Screen Shot 2022-10-15 at 20 31 15

**Pull request merged**
