### PR TITLE
chore: upgrade to Angular 12

### PR DESCRIPTION
**Pull request by arturovt**

### CODE REVIEW

**Comment by NetanelBasal** [comment]
We need to update the node version :)

**Review by NetanelBasal — APPROVED** [review]

**Comment by MickL** [comment]
@NetanelBasal @arturovt Could you please publish to npm? I dont get errors when compiling as a web component since Angular 12.

**Comment by arturovt** [comment]
Could you provide an example where this error is thrown?

**Comment by MickL** [comment]
If you could just publish the latest version to npm maybe the error is fixed

**Comment by arturovt** [comment]
Why can't you just paste the code? I can't publish the new version since I haven't done any code updates.

**Comment by MickL** [comment]
It is not that easy and takes a lot of time to make a repo to reproduce the issue. But I did make the repo and it works as expected.

**Comment by arturovt** [comment]
You don’t have to make a repo, you can just paste your code here or some screenshot where this error is thrown and how the code looks like.

**Comment by arturovt** [comment]
And would be great to paste your package.json with dependencies, I don’t need all dependencies but only that start with `@angular`, rxjs and until-destroy.

**Comment by MickL** [comment]
As I said I made a repo and everything works as expected. Please ignore my initial comment.

**Pull request merged**
