### PR TITLE
feat: make compatible with Angular 10

### LINKED ISSUE #97: Abtract component and UntilDestroy decorator
I have the same issue as [Issue 50](https://github.com/ngneat/until-destroy/issues/50)

I use Angular 9 and the error is
`Cannot read property 'onDestroy' of undefined`

### PR DESCRIPTION
**Pull request by arturovt**
@NetanelBasal I've updated this codebase to Angular 10 and also have to change code since they removed lifecycle hooks from directive/component definitions and now it's possible to patch prototype methods.

Btw it's not possible for pipes, they haven't changed behavior for pipes and `onDestroy` is still stored on the `ɵpipe`.

With this addition I've also fixed #97 issue and #118.

P.S. I'm thinking about reverting that `tsconfig.base.json` change and leaving it as it was before, my VSCode cannot resolve any NPM module :confused: :confused:

### CODE REVIEW

**Comment by bbarry** [comment]
Does this also take care of #118?

**Comment by NetanelBasal** [comment]
@arturovt yes, this is the change I showed you earlier. It simplifies the code. 

> they haven't changed behavior for pipes, and onDestroy is still stored on the ɵpipe.

Maybe it's worth to open an issue about this. They should be consistent. There is a chance that they missed it.

> P.S. I'm thinking about reverting that tsconfig.base.json change and leaving it as it was before, my VSCode cannot resolve any NPM module 😕 😕

As you wish.

**Comment by NetanelBasal** [comment]
@bbarry yes, it does.

**Comment by NetanelBasal** [comment]
@arturovt when publishing don't forget to bump a major version :)

**Comment by NetanelBasal** [comment]
@arturovt I think we can get rid of the decorator. I don't mind dropping the Pipe support for this one.

**Comment by arturovt** [comment]
> @arturovt I think we can get rid of the decorator. I don't mind dropping the Pipe support for this one.

Yeah. I propose to publish 8.0.0 which will require `@angular/core >= 10` since I see that people faced that issue. And the we could publish new version where we could exclude decorator. Wtyd?

**Comment by NetanelBasal** [comment]
Yes. Finally, it will be simple as calling `untilDestroy(this)`

**Comment by arturovt** [comment]
I will double check integration examples this evening and will merge & publish.

**Pull request merged**
