### PR TITLE
feat: upgrade to Angular 13

### PR DESCRIPTION
**Pull request by arturovt**

### CODE REVIEW

**Comment by bbarry** [comment]
Is there a break you are anticipating or some existing incompatibility?

**Comment by arturovt** [comment]
@bbarry hey, what do you mean?

**Comment by arturovt** [comment]
> I don't think I saw anything change in this repo that would make 8x not work with 13 or 9x not work with <13

Do you mean that change: https://github.com/ngneat/until-destroy/commit/c9f5039f455ea8b81423a72801e4f98bea533846 ?

**Comment by bbarry** [comment]
I guess so. I only noticed it due to the readme change here in this pr. 

A few projects I am depending on have made similar changes to this and I'm beginning to get a little concerned that I missed something in the Angular changes that made 13 a bigger release than 11 and 12 were. In this project I remember the incompatibility fixed with the 10.0.5 requirement and was wondering if there was something in 13 that necessitated the new requirement that I should be paying more attention to.

I'm not arguing against it or anything like that; I think it is fine to align a major version update with a major version update for the sake of simplicity.

**Comment by arturovt** [comment]
It was bumped with a major version because of the modern Angular package format (https://angular.io/guide/angular-package-format); it's not compatible with older Angular versions. Older versions of Webpack can resolve `.mjs` files, but, e.g. Jest cannot resolve `.mjs` files so that tests will be broken.

**Pull request merged**
